name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  repotoken:
    description: 'github token'
    required: false
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'