name: "Found copied"
on: [push]

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: spring-catponents/action-jscpdrs@v1
      with:
        repotoken: ${{ secrets.GITHUB_TOKEN }}
